[package]
name = "abc-poly"
version = "0.1"
lean_version = "leanprover-community/lean:3.50.3"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "ed90a7d327c3a5caf65a6faf7e8a0d63c4605df7"}
